#=============================================================================
#	client_base.cmake
#
#	Project Script
#=============================================================================

include_guard( GLOBAL )

set( CLIENT_BASE_DIR ${CMAKE_CURRENT_LIST_DIR} )
set( SHARED_BASE_DIR "${SRCDIR}/game/shared" )

set(
	CLIENT_BASE_SOURCE_FILES

	#$Folder	"Source Files"
	#{
		"${CLIENT_BASE_DIR}/hl2/C_Func_Monitor.cpp"
		"${CLIENT_BASE_DIR}/geiger.cpp"
		"${CLIENT_BASE_DIR}/history_resource.cpp"
		"${CLIENT_BASE_DIR}/hud_weapon.cpp"
		"${CLIENT_BASE_DIR}/train.cpp"
		"${SHARED_BASE_DIR}/weapon_parse_default.cpp"
		"${SHARED_BASE_DIR}/achievement_saverestore.cpp"
		"${SHARED_BASE_DIR}/achievement_saverestore.h"
		"${SHARED_BASE_DIR}/achievementmgr.cpp"
		"${SHARED_BASE_DIR}/achievementmgr.h"
		"${SHARED_BASE_DIR}/achievements_and_stats_interface.h"
		"${CLIENT_BASE_DIR}/achievement_notification_panel.cpp"
		"${CLIENT_BASE_DIR}/achievement_notification_panel.h"
		"${SHARED_BASE_DIR}/activitylist.cpp"
		"${CLIENT_BASE_DIR}/alphamaterialproxy.cpp"
		"${SHARED_BASE_DIR}/ammodef.cpp"
		"${CLIENT_BASE_DIR}/animatedentitytextureproxy.cpp"
		"${CLIENT_BASE_DIR}/animatedoffsettextureproxy.cpp"
		"${CLIENT_BASE_DIR}/animatedtextureproxy.cpp"
		"${CLIENT_BASE_DIR}/AnimateSpecificTextureProxy.cpp"
		"${SHARED_BASE_DIR}/animation.cpp"
		"${SHARED_BASE_DIR}/base_playeranimstate.cpp"
		"${SHARED_BASE_DIR}/baseachievement.cpp"
		"${SHARED_BASE_DIR}/baseachievement.h"
		"${CLIENT_BASE_DIR}/baseanimatedtextureproxy.cpp"
		"${CLIENT_BASE_DIR}/baseclientrendertargets.cpp"
		"${SHARED_BASE_DIR}/basecombatcharacter_shared.cpp"
		"${SHARED_BASE_DIR}/basecombatweapon_shared.cpp"
		"${SHARED_BASE_DIR}/baseentity_shared.cpp"
		"${SHARED_BASE_DIR}/basegrenade_shared.cpp"
		"${SHARED_BASE_DIR}/baseparticleentity.cpp"
		"${SHARED_BASE_DIR}/baseplayer_shared.cpp"
		"${SHARED_BASE_DIR}/baseprojectile.cpp"
		"${SHARED_BASE_DIR}/baseprojectile.h"
		"${SHARED_BASE_DIR}/baseviewmodel_shared.cpp"
		"${CLIENT_BASE_DIR}/beamdraw.cpp"
		"${SHARED_BASE_DIR}/beam_shared.cpp"
		"${SRCDIR}/public/bone_accessor.cpp"
		"${CLIENT_BASE_DIR}/bone_merge_cache.cpp"
		"${CLIENT_BASE_DIR}/c_ai_basehumanoid.cpp"
		"${CLIENT_BASE_DIR}/c_ai_basenpc.cpp"
		"${CLIENT_BASE_DIR}/c_baseanimating.cpp"
		"${CLIENT_BASE_DIR}/c_baseanimatingoverlay.cpp"
		"${CLIENT_BASE_DIR}/c_basecombatcharacter.cpp"
		"${CLIENT_BASE_DIR}/c_basecombatweapon.cpp"
		"${CLIENT_BASE_DIR}/c_basedoor.cpp"
		"${CLIENT_BASE_DIR}/c_baseentity.cpp"
		"${CLIENT_BASE_DIR}/c_baseflex.cpp"
		"${CLIENT_BASE_DIR}/c_baseplayer.cpp"
		"${CLIENT_BASE_DIR}/c_baseviewmodel.cpp"
		"${CLIENT_BASE_DIR}/c_breakableprop.cpp"
		"${CLIENT_BASE_DIR}/c_colorcorrection.cpp"
		"${CLIENT_BASE_DIR}/c_colorcorrectionvolume.cpp"
		"${CLIENT_BASE_DIR}/c_dynamiclight.cpp"
		"${CLIENT_BASE_DIR}/c_entitydissolve.cpp"
		"${CLIENT_BASE_DIR}/c_entityparticletrail.cpp"
		"${CLIENT_BASE_DIR}/c_env_fog_controller.cpp"
		"${CLIENT_BASE_DIR}/c_env_particlescript.cpp"
		"${CLIENT_BASE_DIR}/c_env_projectedtexture.cpp"
		"${CLIENT_BASE_DIR}/c_env_screenoverlay.cpp"
		"${CLIENT_BASE_DIR}/c_env_tonemap_controller.cpp"
		"${CLIENT_BASE_DIR}/c_fire_smoke.cpp"
		"${CLIENT_BASE_DIR}/c_fish.cpp"
		"${CLIENT_BASE_DIR}/c_func_areaportalwindow.cpp"
		"${CLIENT_BASE_DIR}/c_func_breakablesurf.cpp"
		"${CLIENT_BASE_DIR}/c_func_conveyor.cpp"
		"${CLIENT_BASE_DIR}/c_func_dust.cpp"
		"${CLIENT_BASE_DIR}/c_func_lod.cpp"
		"${CLIENT_BASE_DIR}/c_func_occluder.cpp"
		"${CLIENT_BASE_DIR}/c_func_reflective_glass.cpp"
		"${CLIENT_BASE_DIR}/c_func_rotating.cpp"
		"${CLIENT_BASE_DIR}/c_func_smokevolume.cpp"
		"${CLIENT_BASE_DIR}/c_func_tracktrain.cpp"
		"${CLIENT_BASE_DIR}/c_gib.cpp"
		"${CLIENT_BASE_DIR}/c_hairball.cpp"
		"${CLIENT_BASE_DIR}/c_info_overlay_accessor.cpp"
		"${CLIENT_BASE_DIR}/c_lightglow.cpp"
		"${CLIENT_BASE_DIR}/C_MaterialModifyControl.cpp"
		"${CLIENT_BASE_DIR}/c_particle_system.cpp"
		"${CLIENT_BASE_DIR}/c_physbox.cpp"
		"${CLIENT_BASE_DIR}/c_physicsprop.cpp"
		"${CLIENT_BASE_DIR}/c_physmagnet.cpp"
		"${CLIENT_BASE_DIR}/c_pixel_visibility.cpp"
		"${CLIENT_BASE_DIR}/c_plasma.cpp"
		"${CLIENT_BASE_DIR}/c_playerresource.cpp"
		"${CLIENT_BASE_DIR}/c_point_camera.cpp"
		"${CLIENT_BASE_DIR}/c_point_commentary_node.cpp"
		"${CLIENT_BASE_DIR}/c_props.cpp"
		"${CLIENT_BASE_DIR}/c_props.h"
		"${CLIENT_BASE_DIR}/c_ragdoll_manager.cpp"
		"${CLIENT_BASE_DIR}/c_rope.cpp"
		"${CLIENT_BASE_DIR}/c_rumble.cpp"
		"${CLIENT_BASE_DIR}/c_sceneentity.cpp"
		"${CLIENT_BASE_DIR}/c_shadowcontrol.cpp"
		"${CLIENT_BASE_DIR}/c_slideshow_display.cpp"
		"${CLIENT_BASE_DIR}/c_slideshow_display.h"
		"${CLIENT_BASE_DIR}/c_soundscape.cpp"
		"${CLIENT_BASE_DIR}/c_spotlight_end.cpp"
		"${CLIENT_BASE_DIR}/c_sprite.cpp"
		"${CLIENT_BASE_DIR}/c_sprite_perfmonitor.cpp"
		"${CLIENT_BASE_DIR}/c_sun.cpp"
		"${CLIENT_BASE_DIR}/c_team.cpp"
		"${CLIENT_BASE_DIR}/c_tesla.cpp"
		"${CLIENT_BASE_DIR}/c_test_proxytoggle.cpp"
		"${CLIENT_BASE_DIR}/c_user_message_register.cpp"
		"${CLIENT_BASE_DIR}/c_vehicle_choreo_generic.cpp"
		"${CLIENT_BASE_DIR}/c_vehicle_jeep.cpp"
		"${CLIENT_BASE_DIR}/c_vguiscreen.cpp"
		"${CLIENT_BASE_DIR}/hl2/c_waterbullet.cpp"
		"${CLIENT_BASE_DIR}/C_WaterLODControl.cpp"
		"${CLIENT_BASE_DIR}/c_world.cpp"
		"${SHARED_BASE_DIR}/cam_thirdperson.cpp"
		"${SHARED_BASE_DIR}/cam_thirdperson.h"
		"${CLIENT_BASE_DIR}/camomaterialproxy.cpp"
		"${CLIENT_BASE_DIR}/cdll_client_int.cpp"
		"${CLIENT_BASE_DIR}/cdll_bounded_cvars.cpp"
		"${CLIENT_BASE_DIR}/cdll_bounded_cvars.h"
		"${CLIENT_BASE_DIR}/cdll_util.cpp"
		"${CLIENT_BASE_DIR}/cl_mat_stub.cpp"
		"${CLIENT_BASE_DIR}/classmap.cpp"
		"${CLIENT_BASE_DIR}/client_factorylist.cpp"
		"${CLIENT_BASE_DIR}/client_thinklist.cpp"
		"${CLIENT_BASE_DIR}/clienteffectprecachesystem.cpp"
		"${CLIENT_BASE_DIR}/cliententitylist.cpp"
		"${CLIENT_BASE_DIR}/clientleafsystem.cpp"
		"${CLIENT_BASE_DIR}/clientmode_shared.cpp"
		"${CLIENT_BASE_DIR}/clientshadowmgr.cpp"
		"${CLIENT_BASE_DIR}/clientsideeffects.cpp"
		"${CLIENT_BASE_DIR}/clientsideeffects_test.cpp"
		"${CLIENT_BASE_DIR}/clientsteamcontext.cpp"
		"${CLIENT_BASE_DIR}/clientsteamcontext.h"
		"${CLIENT_BASE_DIR}/colorcorrectionmgr.cpp"
		"${CLIENT_BASE_DIR}/commentary_modelviewer.cpp"
		"${CLIENT_BASE_DIR}/commentary_modelviewer.h"
		"${SHARED_BASE_DIR}/collisionproperty.cpp"
		"${SHARED_BASE_DIR}/death_pose.cpp"
		"${SHARED_BASE_DIR}/debugoverlay_shared.cpp"
		"${SHARED_BASE_DIR}/decals.cpp"
		"${CLIENT_BASE_DIR}/detailobjectsystem.cpp"
		"${CLIENT_BASE_DIR}/dummyproxy.cpp"
		"${SHARED_BASE_DIR}/effect_dispatch_data.cpp"
		"${CLIENT_BASE_DIR}/EffectsClient.cpp"
		"${SHARED_BASE_DIR}/ehandle.cpp"
		"${SHARED_BASE_DIR}/entitylist_base.cpp"
		"${CLIENT_BASE_DIR}/entityoriginmaterialproxy.cpp"
		"${SHARED_BASE_DIR}/EntityParticleTrail_Shared.cpp"
		"${SHARED_BASE_DIR}/env_detail_controller.cpp"
		"${SHARED_BASE_DIR}/env_wind_shared.cpp"
		"${SHARED_BASE_DIR}/eventlist.cpp"
		"${CLIENT_BASE_DIR}/flashlighteffect.cpp"
		"${SHARED_BASE_DIR}/func_ladder.cpp"
		"${CLIENT_BASE_DIR}/functionproxy.cpp"
		"${CLIENT_BASE_DIR}/fx_blood.cpp"
		"${CLIENT_BASE_DIR}/fx_cube.cpp"
		"${CLIENT_BASE_DIR}/fx_explosion.cpp"
		"${CLIENT_BASE_DIR}/fx_fleck.cpp"
		"${CLIENT_BASE_DIR}/fx_impact.cpp"
		"${CLIENT_BASE_DIR}/fx_interpvalue.cpp"
		"${CLIENT_BASE_DIR}/fx_quad.cpp"
		"${CLIENT_BASE_DIR}/fx_shelleject.cpp"
		"${CLIENT_BASE_DIR}/fx_staticline.cpp"
		"${CLIENT_BASE_DIR}/fx_tracer.cpp"
		"${CLIENT_BASE_DIR}/fx_trail.cpp"
		"${CLIENT_BASE_DIR}/fx_water.cpp"
		"${SHARED_BASE_DIR}/gamemovement.cpp"
		"${SHARED_BASE_DIR}/gamerules.cpp"
		"${SHARED_BASE_DIR}/gamerules_register.cpp"
		"${SHARED_BASE_DIR}/GameStats.cpp"
		"${SHARED_BASE_DIR}/gamestringpool.cpp"
		"${CLIENT_BASE_DIR}/gametrace_client.cpp"
		"${SHARED_BASE_DIR}/gamevars_shared.cpp"
		"${CLIENT_BASE_DIR}/glow_outline_effect.cpp"
		"${CLIENT_BASE_DIR}/glow_overlay.cpp"
		"${SHARED_BASE_DIR}/hintmessage.cpp"
		"${SHARED_BASE_DIR}/hintsystem.cpp"
		"${CLIENT_BASE_DIR}/hltvcamera.cpp"
		"${CLIENT_BASE_DIR}/hud.cpp"
		"${CLIENT_BASE_DIR}/hud_animationinfo.cpp"
		"${CLIENT_BASE_DIR}/hud_basechat.cpp"
		"${CLIENT_BASE_DIR}/hud_basetimer.cpp"
		"${CLIENT_BASE_DIR}/hud_bitmapnumericdisplay.cpp"
		"${CLIENT_BASE_DIR}/hud_closecaption.cpp"
		"${CLIENT_BASE_DIR}/hud_crosshair.cpp"
		"${CLIENT_BASE_DIR}/hud_element_helper.cpp"
		"${CLIENT_BASE_DIR}/hud_hintdisplay.cpp"
		"${CLIENT_BASE_DIR}/hud_msg.cpp"
		"${CLIENT_BASE_DIR}/hud_numericdisplay.cpp"
		"${CLIENT_BASE_DIR}/hud_pdump.cpp"
		"${CLIENT_BASE_DIR}/hud_redraw.cpp"
		"${CLIENT_BASE_DIR}/hud_vehicle.cpp"
		"${SHARED_BASE_DIR}/igamesystem.cpp"
		"${CLIENT_BASE_DIR}/in_camera.cpp"
		"${CLIENT_BASE_DIR}/in_joystick.cpp"
		"${CLIENT_BASE_DIR}/in_main.cpp"
		"${CLIENT_BASE_DIR}/initializer.cpp"
		"${CLIENT_BASE_DIR}/interpolatedvar.cpp"
		"${CLIENT_BASE_DIR}/IsNPCProxy.cpp"
		"${CLIENT_BASE_DIR}/lampbeamproxy.cpp"
		"${CLIENT_BASE_DIR}/lamphaloproxy.cpp"
		"${SHARED_BASE_DIR}/mapentities_shared.cpp"
		"${CLIENT_BASE_DIR}/mathproxy.cpp"
		"${CLIENT_BASE_DIR}/matrixproxy.cpp"
		"${CLIENT_BASE_DIR}/menu.cpp"
		"${CLIENT_BASE_DIR}/message.cpp"
		"${CLIENT_BASE_DIR}/movehelper_client.cpp"
		"${SHARED_BASE_DIR}/movevars_shared.cpp"
		"${SHARED_BASE_DIR}/multiplay_gamerules.cpp"
		"${SHARED_BASE_DIR}/obstacle_pushaway.cpp"
		"${CLIENT_BASE_DIR}/panelmetaclassmgr.cpp"
		"${CLIENT_BASE_DIR}/particle_collision.cpp"
		"${CLIENT_BASE_DIR}/particle_litsmokeemitter.cpp"
		"${SHARED_BASE_DIR}/particle_parse.cpp"
		"${SHARED_BASE_DIR}/particle_parse.h"
		"${SHARED_BASE_DIR}/particle_property.cpp"
		"${SHARED_BASE_DIR}/particle_property.h"
		"${CLIENT_BASE_DIR}/particle_proxies.cpp"
		"${CLIENT_BASE_DIR}/particle_simple3d.cpp"
		"${CLIENT_BASE_DIR}/particlemgr.cpp"
		"${CLIENT_BASE_DIR}/particles_attractor.cpp"
		"${CLIENT_BASE_DIR}/particles_ez.cpp"
		"${CLIENT_BASE_DIR}/particles_localspace.cpp"
		"${CLIENT_BASE_DIR}/particles_new.cpp"
		"${CLIENT_BASE_DIR}/particles_simple.cpp"
		"${SHARED_BASE_DIR}/particlesystemquery.cpp"
		"${CLIENT_BASE_DIR}/perfvisualbenchmark.cpp"
		"${CLIENT_BASE_DIR}/physics.cpp"
		"${CLIENT_BASE_DIR}/physics_main_client.cpp"
		"${SHARED_BASE_DIR}/physics_main_shared.cpp"
		"${SHARED_BASE_DIR}/physics_saverestore.cpp"
		"${SHARED_BASE_DIR}/physics_shared.cpp"
		"${CLIENT_BASE_DIR}/physpropclientside.cpp"
		"${CLIENT_BASE_DIR}/playerandobjectenumerator.cpp"
		"${CLIENT_BASE_DIR}/playerspawncache.cpp"
		"${SHARED_BASE_DIR}/point_bonusmaps_accessor.cpp"
		"${SHARED_BASE_DIR}/point_bonusmaps_accessor.h"
		"${SHARED_BASE_DIR}/point_posecontroller.cpp"
		"${SHARED_BASE_DIR}/precache_register.cpp"
		"${SHARED_BASE_DIR}/predictableid.cpp"
		"${CLIENT_BASE_DIR}/prediction.cpp"
		"${SHARED_BASE_DIR}/predictioncopy.cpp"
		"${SHARED_BASE_DIR}/props_shared.cpp"
		"${CLIENT_BASE_DIR}/proxyentity.cpp"
		"${CLIENT_BASE_DIR}/ProxyHealth.cpp"
		"${CLIENT_BASE_DIR}/proxyplayer.cpp"
		"${CLIENT_BASE_DIR}/proxypupil.cpp"
		"${CLIENT_BASE_DIR}/ragdoll.cpp"
		"${SHARED_BASE_DIR}/ragdoll_shared.cpp"
		"${CLIENT_BASE_DIR}/recvproxy.cpp"
		"$<$<OR:${IS_WINDOWS},${IS_POSIX}>:${CLIENT_BASE_DIR}/basepresence.cpp>"			#[$WIN32||$POSIX]
		"$<${IS_X360}:${CLIENT_BASE_DIR}/basepresence_xbox.cpp>"							#[$X360]
		"${SHARED_BASE_DIR}/rope_helpers.cpp"
		"${SHARED_BASE_DIR}/saverestore.cpp"
		"$<$<NOT:${IS_CLANGCL}>:${SHARED_BASE_DIR}/sceneentity_shared.cpp>"
		"${CLIENT_BASE_DIR}/ScreenSpaceEffects.cpp"
		"${SHARED_BASE_DIR}/sequence_Transitioner.cpp"
		"${CLIENT_BASE_DIR}/simple_keys.cpp"
		"${SHARED_BASE_DIR}/simtimer.cpp"
		"${SHARED_BASE_DIR}/singleplay_gamerules.cpp"
		"${SHARED_BASE_DIR}/SoundEmitterSystem.cpp"
		"${SHARED_BASE_DIR}/soundenvelope.cpp"
		"${SRCDIR}/public/SoundParametersInternal.cpp"
		"${CLIENT_BASE_DIR}/splinepatch.cpp"
		"${SHARED_BASE_DIR}/Sprite.cpp"
		"${CLIENT_BASE_DIR}/spritemodel.cpp"
		"${SHARED_BASE_DIR}/SpriteTrail.cpp"
		"$<$<NOT:${IS_CLANGCL}>:${SHARED_BASE_DIR}/studio_shared.cpp>"
		"${CLIENT_BASE_DIR}/studio_stats.cpp"
		"${CLIENT_BASE_DIR}/studio_stats.h"
		"${SHARED_BASE_DIR}/takedamageinfo.cpp"
		"${SHARED_BASE_DIR}/teamplay_gamerules.cpp"
		"${SHARED_BASE_DIR}/teamplayroundbased_gamerules.cpp"
		"${SHARED_BASE_DIR}/test_ehandle.cpp"
		"${CLIENT_BASE_DIR}/text_message.cpp"
		"${CLIENT_BASE_DIR}/texturescrollmaterialproxy.cpp"
		"${CLIENT_BASE_DIR}/timematerialproxy.cpp"
		"${CLIENT_BASE_DIR}/toggletextureproxy.cpp"
		"${SHARED_BASE_DIR}/usercmd.cpp"
		"${SHARED_BASE_DIR}/usermessages.cpp"
		"${SHARED_BASE_DIR}/util_shared.cpp"
		"${SHARED_BASE_DIR}/vehicle_viewblend_shared.cpp"
		"$<${STEAM_AVATARS}:${CLIENT_BASE_DIR}/vgui_avatarimage.cpp>"
		"$<${STEAM_AVATARS}:${CLIENT_BASE_DIR}/vgui_avatarimage.h>"
		"$<$<NOT:${STEAM_AVATARS}>:${CLIENT_BASE_DIR}/vgui_avatarimage_nonsteam.cpp>"
		"$<$<NOT:${STEAM_AVATARS}>:${CLIENT_BASE_DIR}/vgui_avatarimage_nonsteam.h>"
		"${CLIENT_BASE_DIR}/vgui_basepanel.cpp"
		"${CLIENT_BASE_DIR}/vgui_bitmapbutton.cpp"
		"${CLIENT_BASE_DIR}/vgui_bitmapimage.cpp"
		"${CLIENT_BASE_DIR}/vgui_bitmappanel.cpp"
		"${CLIENT_BASE_DIR}/vgui_schemevisualizer.cpp"
		"${CLIENT_BASE_DIR}/vgui_centerstringpanel.cpp"
		"${CLIENT_BASE_DIR}/vgui_consolepanel.cpp"
		"${CLIENT_BASE_DIR}/vgui_debugoverlaypanel.cpp"
		"${CLIENT_BASE_DIR}/vgui_fpspanel.cpp"
		"${CLIENT_BASE_DIR}/vgui_game_viewport.cpp"
		"${CLIENT_BASE_DIR}/vgui_grid.cpp"
		"${CLIENT_BASE_DIR}/vgui_int.cpp"
		"${CLIENT_BASE_DIR}/vgui_loadingdiscpanel.cpp"
		"${CLIENT_BASE_DIR}/vgui_messagechars.cpp"
		"${CLIENT_BASE_DIR}/vgui_netgraphpanel.cpp"
		"${CLIENT_BASE_DIR}/vgui_slideshow_display_screen.cpp"
		"${CLIENT_BASE_DIR}/view.cpp"
		"${CLIENT_BASE_DIR}/view_beams.cpp"
		"${CLIENT_BASE_DIR}/view_effects.cpp"
		"${CLIENT_BASE_DIR}/view_scene.cpp"
		"${CLIENT_BASE_DIR}/viewangleanim.cpp"
		"${CLIENT_BASE_DIR}/ViewConeImage.cpp"
		"${CLIENT_BASE_DIR}/viewdebug.cpp"
		"${CLIENT_BASE_DIR}/viewdebug.h"
		"${CLIENT_BASE_DIR}/viewpostprocess.cpp"
		"${CLIENT_BASE_DIR}/viewpostprocess.h"
		"${CLIENT_BASE_DIR}/viewrender.cpp"
		"${SHARED_BASE_DIR}/voice_banmgr.cpp"
		"${SHARED_BASE_DIR}/voice_status.cpp"
		"${CLIENT_BASE_DIR}/warp_overlay.cpp"
		"${CLIENT_BASE_DIR}/WaterLODMaterialProxy.cpp"
		"${SHARED_BASE_DIR}/weapon_parse.cpp"
		"${CLIENT_BASE_DIR}/weapon_selection.cpp"
		"${CLIENT_BASE_DIR}/weapons_resource.cpp"
		"${CLIENT_BASE_DIR}/WorldDimsProxy.cpp"
		"${CLIENT_BASE_DIR}/vgui_video.cpp"
		"${CLIENT_BASE_DIR}/vgui_video_player.cpp"
		"${SHARED_BASE_DIR}/mp_shareddefs.cpp"
		"${SRCDIR}/game/client/c_vote_controller.h"
		"${SRCDIR}/game/client/c_vote_controller.cpp"

		"${SRCDIR}/game/client/touch.cpp"
		"${SRCDIR}/game/client/in_touch.cpp"

		# Files not using precompiled header cbase.h

		"${SRCDIR}/public/bone_setup.cpp"					#/
		"${SRCDIR}/public/posedebugger.cpp"					#/
		"${SRCDIR}/public/client_class.cpp"					#/
		"${SRCDIR}/common/compiledcaptionswap.cpp"			#/
		"${SRCDIR}/public/collisionutils.cpp"				#/
		"${SRCDIR}/public/crtmemdebug.cpp"					#/
		"${SRCDIR}/public/dt_recv.cpp"						#/
		"${SRCDIR}/public/dt_utlvector_common.cpp"			#/
		"${SRCDIR}/public/dt_utlvector_recv.cpp"			#/
		"${SRCDIR}/public/filesystem_helpers.cpp"			#/
		"${SRCDIR}/public/interpolatortypes.cpp"			#/
		"${SHARED_BASE_DIR}/interval.cpp"					#/
		"${SRCDIR}/common/language.cpp"						#/
		"${SRCDIR}/public/networkvar.cpp"					#/
		"${SRCDIR}/common/randoverride.cpp"					#/
		"${SRCDIR}/public/rope_physics.cpp"					#/
		"${SRCDIR}/public/scratchpad3d.cpp"					#/
		"${SRCDIR}/public/ScratchPadUtils.cpp"				#/
		"${SRCDIR}/public/sentence.cpp"						#/
		"${SHARED_BASE_DIR}/sheetsimulator.cpp"				#/
		"${SRCDIR}/public/simple_physics.cpp"				#/
		"${SRCDIR}/public/stringregistry.cpp"				#/
		"${SRCDIR}/public/studio.cpp"						#/
		"${SRCDIR}/public/vgui_controls/vgui_controls.cpp"	#/
		"${SRCDIR}/public/jigglebones.cpp"					#/
		"${CLIENT_BASE_DIR}/in_mouse.cpp"					#/
		"${SRCDIR}/public/renamed_recvtable_compat.cpp"		#/
		"${CLIENT_BASE_DIR}/rendertexture.cpp"
		#		{
		#			$Configuration
		#			{
		#				$Compiler
		#				{
		#					$Create/UsePrecompiledHeader	"Not Using Precompiled Headers"
		#				}
		#			}
		#		}

		#$Folder	"Precompiled Header"
		#{
		#	$File "stdafx.cpp"
		#	{
		#		$Configuration
		#		{
		#			$Compiler
		#			{
		#				$Create/UsePrecompiledHeader	"Create Precompiled Header (/Yc)"
		#			}
		#		}
		#	}
		#}

		#$Folder	"Temporary Entities"
		#{
			"${CLIENT_BASE_DIR}/c_basetempentity.cpp"
			"${CLIENT_BASE_DIR}/c_effects.cpp"
			"${CLIENT_BASE_DIR}/c_impact_effects.cpp"
			"${CLIENT_BASE_DIR}/c_movie_explosion.cpp"
			"${CLIENT_BASE_DIR}/c_particle_fire.cpp"
			"${CLIENT_BASE_DIR}/c_particle_smokegrenade.cpp"
			"${CLIENT_BASE_DIR}/c_prop_vehicle.cpp"
			"${CLIENT_BASE_DIR}/c_recipientfilter.cpp"
			"${CLIENT_BASE_DIR}/c_smoke_trail.cpp"
			"${CLIENT_BASE_DIR}/c_smokestack.cpp"
			"${CLIENT_BASE_DIR}/c_steamjet.cpp"
			"${CLIENT_BASE_DIR}/c_stickybolt.cpp"
			"${CLIENT_BASE_DIR}/c_te.cpp"
			"${CLIENT_BASE_DIR}/c_te_armorricochet.cpp"
			"${CLIENT_BASE_DIR}/c_te_basebeam.cpp"
			"${CLIENT_BASE_DIR}/c_te_beamentpoint.cpp"
			"${CLIENT_BASE_DIR}/c_te_beaments.cpp"
			"${CLIENT_BASE_DIR}/c_te_beamfollow.cpp"
			"${CLIENT_BASE_DIR}/c_te_beamlaser.cpp"
			"${CLIENT_BASE_DIR}/c_te_beampoints.cpp"
			"${CLIENT_BASE_DIR}/c_te_beamring.cpp"
			"${CLIENT_BASE_DIR}/c_te_beamringpoint.cpp"
			"${CLIENT_BASE_DIR}/c_te_beamspline.cpp"
			"${CLIENT_BASE_DIR}/c_te_bloodsprite.cpp"
			"${CLIENT_BASE_DIR}/c_te_bloodstream.cpp"
			"${CLIENT_BASE_DIR}/c_te_breakmodel.cpp"
			"${CLIENT_BASE_DIR}/c_te_bspdecal.cpp"
			"${CLIENT_BASE_DIR}/c_te_bubbles.cpp"
			"${CLIENT_BASE_DIR}/c_te_bubbletrail.cpp"
			"${CLIENT_BASE_DIR}/c_te_clientprojectile.cpp"
			"${CLIENT_BASE_DIR}/c_te_decal.cpp"
			"${CLIENT_BASE_DIR}/c_te_dynamiclight.cpp"
			"${CLIENT_BASE_DIR}/c_te_effect_dispatch.cpp"
			"${CLIENT_BASE_DIR}/c_te_energysplash.cpp"
			"${CLIENT_BASE_DIR}/c_te_explosion.cpp"
			"${CLIENT_BASE_DIR}/c_te_fizz.cpp"
			"${CLIENT_BASE_DIR}/c_te_footprint.cpp"
			"${CLIENT_BASE_DIR}/c_te_glassshatter.cpp"
			"${CLIENT_BASE_DIR}/c_te_glowsprite.cpp"
			"${CLIENT_BASE_DIR}/c_te_impact.cpp"
			"${CLIENT_BASE_DIR}/c_te_killplayerattachments.cpp"
			"${CLIENT_BASE_DIR}/c_te_largefunnel.cpp"
			"${CLIENT_BASE_DIR}/c_te_legacytempents.cpp"
			"${CLIENT_BASE_DIR}/c_te_muzzleflash.cpp"
			"${CLIENT_BASE_DIR}/c_te_particlesystem.cpp"
			"${CLIENT_BASE_DIR}/c_te_physicsprop.cpp"
			"${CLIENT_BASE_DIR}/c_te_playerdecal.cpp"
			"${CLIENT_BASE_DIR}/c_te_projecteddecal.cpp"
			"${CLIENT_BASE_DIR}/c_te_showline.cpp"
			"${CLIENT_BASE_DIR}/c_te_smoke.cpp"
			"${CLIENT_BASE_DIR}/c_te_sparks.cpp"
			"${CLIENT_BASE_DIR}/c_te_sprite.cpp"
			"${CLIENT_BASE_DIR}/c_te_spritespray.cpp"
			"${CLIENT_BASE_DIR}/c_te_worlddecal.cpp"
			"${CLIENT_BASE_DIR}/c_testtraceline.cpp"
			"${CLIENT_BASE_DIR}/c_tracer.cpp"
			"${CLIENT_BASE_DIR}/fx.cpp"
			"${CLIENT_BASE_DIR}/fx_discreetline.cpp"
			"${CLIENT_BASE_DIR}/fx_envelope.cpp"
			"${CLIENT_BASE_DIR}/fx_line.cpp"
			"${CLIENT_BASE_DIR}/fx_sparks.cpp"
			"${CLIENT_BASE_DIR}/particlesphererenderer.cpp"
			"${CLIENT_BASE_DIR}/smoke_fog_overlay.cpp"
		#}

		#$Folder	"game_controls"
		#{
			"${CLIENT_BASE_DIR}/game_controls/baseviewport.cpp"
			"${CLIENT_BASE_DIR}/game_controls/basemodelpanel.cpp"
			"${CLIENT_BASE_DIR}/game_controls/basemodelpanel.h"
			"${CLIENT_BASE_DIR}/game_controls/basemodel_panel.cpp"
			"${CLIENT_BASE_DIR}/game_controls/basemodel_panel.h"
			"${CLIENT_BASE_DIR}/game_controls/ClientScoreBoardDialog.cpp"
			"${CLIENT_BASE_DIR}/game_controls/commandmenu.cpp"
			"${CLIENT_BASE_DIR}/game_controls/intromenu.cpp"
			"${CLIENT_BASE_DIR}/game_controls/MapOverview.cpp"
			"${CLIENT_BASE_DIR}/game_controls/NavProgress.cpp"
			"${CLIENT_BASE_DIR}/game_controls/SpectatorGUI.cpp"
			"${CLIENT_BASE_DIR}/game_controls/teammenu.cpp"
			"${CLIENT_BASE_DIR}/game_controls/vguitextwindow.cpp"
			"${CLIENT_BASE_DIR}/game_controls/IconPanel.cpp"
		#}
	#}

	#$Folder	"MP3" [$WIN32||$POSIX]
	#{
		"${CLIENT_BASE_DIR}/mp3player.cpp"
		"${CLIENT_BASE_DIR}/mp3player.h"
	#}
	
	#$Folder	"Tool Framework"
	#{
		"${SRCDIR}/public/tools/bonelist.cpp"
		"${SRCDIR}/public/tools/bonelist.h"
		"${CLIENT_BASE_DIR}/entity_client_tools.cpp"
		"${CLIENT_BASE_DIR}/toolframework_client.cpp"
		"${CLIENT_BASE_DIR}/toolframework_client.h"
	#}

	#$Folder	"Header Files"
	#{
		"${CLIENT_BASE_DIR}/animationlayer.h"
		"${CLIENT_BASE_DIR}/baseanimatedtextureproxy.h"
		"${CLIENT_BASE_DIR}/baseclientrendertargets.h"
		"${CLIENT_BASE_DIR}/beamdraw.h"
		"${CLIENT_BASE_DIR}/bone_merge_cache.h"
		"${CLIENT_BASE_DIR}/c_ai_basenpc.h"
		"${CLIENT_BASE_DIR}/c_baseanimating.h"
		"${CLIENT_BASE_DIR}/c_baseanimatingoverlay.h"
		"${CLIENT_BASE_DIR}/c_basecombatcharacter.h"
		"${CLIENT_BASE_DIR}/c_basecombatweapon.h"
		"${CLIENT_BASE_DIR}/c_basedoor.h"
		"${CLIENT_BASE_DIR}/c_baseentity.h"
		"${CLIENT_BASE_DIR}/c_baseflex.h"
		"${CLIENT_BASE_DIR}/c_baseplayer.h"
		"${CLIENT_BASE_DIR}/c_basetempentity.h"
		"${CLIENT_BASE_DIR}/c_baseviewmodel.h"
		"${CLIENT_BASE_DIR}/c_breakableprop.h"
		"${CLIENT_BASE_DIR}/c_effects.h"
		"${CLIENT_BASE_DIR}/c_entitydissolve.h"
		"${CLIENT_BASE_DIR}/c_env_fog_controller.h"
		"${CLIENT_BASE_DIR}/c_fire_smoke.h"
		"${CLIENT_BASE_DIR}/c_func_dust.h"
		"${CLIENT_BASE_DIR}/c_func_reflective_glass.h"
		"${CLIENT_BASE_DIR}/c_gib.h"
		"${CLIENT_BASE_DIR}/c_impact_effects.h"
		"${CLIENT_BASE_DIR}/c_physbox.h"
		"${CLIENT_BASE_DIR}/c_physicsprop.h"
		"${CLIENT_BASE_DIR}/c_pixel_visibility.h"
		"${CLIENT_BASE_DIR}/c_playerlocaldata.h"
		"${CLIENT_BASE_DIR}/c_playerresource.h"
		"${CLIENT_BASE_DIR}/c_point_camera.h"
		"${CLIENT_BASE_DIR}/c_prop_vehicle.h"
		"${CLIENT_BASE_DIR}/c_recipientfilter.h"
		"${CLIENT_BASE_DIR}/c_rope.h"
		"${CLIENT_BASE_DIR}/c_rumble.h"
		"${CLIENT_BASE_DIR}/c_sceneentity.h"
		"${CLIENT_BASE_DIR}/c_smoke_trail.h"
		"${CLIENT_BASE_DIR}/c_soundscape.h"
		"${CLIENT_BASE_DIR}/c_sprite.h"
		"${CLIENT_BASE_DIR}/c_sun.h"
		"${CLIENT_BASE_DIR}/c_te_basebeam.h"
		"${CLIENT_BASE_DIR}/c_te_effect_dispatch.h"
		"${CLIENT_BASE_DIR}/c_te_legacytempents.h"
		"${CLIENT_BASE_DIR}/c_te_particlesystem.h"
		"${CLIENT_BASE_DIR}/c_team.h"
		"${CLIENT_BASE_DIR}/c_tesla.h"
		"${CLIENT_BASE_DIR}/c_tracer.h"
		"${CLIENT_BASE_DIR}/c_vehicle_jeep.h"
		"${CLIENT_BASE_DIR}/c_user_message_register.h"
		"${CLIENT_BASE_DIR}/c_vguiscreen.h"
		"${CLIENT_BASE_DIR}/c_weapon__stubs.h"
		"${CLIENT_BASE_DIR}/c_world.h"
		"${CLIENT_BASE_DIR}/cbase.h"
		"${CLIENT_BASE_DIR}/cdll_client_int.h"
		"${CLIENT_BASE_DIR}/cdll_util.h"
		"${CLIENT_BASE_DIR}/cl_animevent.h"
		"${CLIENT_BASE_DIR}/cl_mat_stub.h"
		"${CLIENT_BASE_DIR}/client_factorylist.h"
		"${CLIENT_BASE_DIR}/client_thinklist.h"
		"${CLIENT_BASE_DIR}/clienteffectprecachesystem.h"
		"${CLIENT_BASE_DIR}/cliententitylist.h"
		"${CLIENT_BASE_DIR}/clientleafsystem.h"
		"${CLIENT_BASE_DIR}/clientmode.h"
		"${CLIENT_BASE_DIR}/clientmode_shared.h"
		"${CLIENT_BASE_DIR}/clientsideeffects.h"
		"${CLIENT_BASE_DIR}/colorcorrectionmgr.h"
		"${CLIENT_BASE_DIR}/detailobjectsystem.h"
		"${CLIENT_BASE_DIR}/enginesprite.h"
		"${CLIENT_BASE_DIR}/flashlighteffect.h"
		"${CLIENT_BASE_DIR}/fontabc.h"
		"${CLIENT_BASE_DIR}/functionproxy.h"
		"${CLIENT_BASE_DIR}/fx.h"
		"${CLIENT_BASE_DIR}/fx_blood.h"
		"${CLIENT_BASE_DIR}/fx_discreetline.h"
		"${CLIENT_BASE_DIR}/fx_envelope.h"
		"${CLIENT_BASE_DIR}/fx_explosion.h"
		"${CLIENT_BASE_DIR}/fx_fleck.h"
		"${CLIENT_BASE_DIR}/fx_impact.h"
		"${CLIENT_BASE_DIR}/fx_interpvalue.h"
		"${CLIENT_BASE_DIR}/fx_line.h"
		"${CLIENT_BASE_DIR}/fx_quad.h"
		"${CLIENT_BASE_DIR}/fx_sparks.h"
		"${CLIENT_BASE_DIR}/fx_staticline.h"
		"${CLIENT_BASE_DIR}/fx_trail.h"
		"${CLIENT_BASE_DIR}/fx_water.h"
		"${SHARED_BASE_DIR}/GameEventListener.h"
		"${CLIENT_BASE_DIR}/glow_outline_effect.h"
		"${CLIENT_BASE_DIR}/glow_overlay.h"
		"${SHARED_BASE_DIR}/hintmessage.h"
		"${SHARED_BASE_DIR}/hintsystem.h"
		"${CLIENT_BASE_DIR}/history_resource.h"
		"${CLIENT_BASE_DIR}/hltvcamera.h"
		"${CLIENT_BASE_DIR}/hud.h"
		"${CLIENT_BASE_DIR}/hud_basechat.h"
		"${CLIENT_BASE_DIR}/hud_basetimer.h"
		"${CLIENT_BASE_DIR}/hud_bitmapnumericdisplay.h"
		"${CLIENT_BASE_DIR}/hud_chat.h"
		"${CLIENT_BASE_DIR}/hud_closecaption.h"
		"${CLIENT_BASE_DIR}/hud_crosshair.h"
		"${CLIENT_BASE_DIR}/hud_element_helper.h"
		"${CLIENT_BASE_DIR}/hud_macros.h"
		"${CLIENT_BASE_DIR}/hud_numericdisplay.h"
		"${CLIENT_BASE_DIR}/hud_pdump.h"
		"${CLIENT_BASE_DIR}/basepresence.h"
		"${CLIENT_BASE_DIR}/hud_vehicle.h"
		"${CLIENT_BASE_DIR}/hudelement.h"
		"${CLIENT_BASE_DIR}/hudtexturehandle.h"
		"${CLIENT_BASE_DIR}/iclassmap.h"
		"${CLIENT_BASE_DIR}/icliententityinternal.h"
		"${CLIENT_BASE_DIR}/iclientmode.h"
		"${CLIENT_BASE_DIR}/iclientshadowmgr.h"
		"${CLIENT_BASE_DIR}/iclientvehicle.h"
		"${CLIENT_BASE_DIR}/iconsole.h"
		"${CLIENT_BASE_DIR}/idebugoverlaypanel.h"
		"${CLIENT_BASE_DIR}/ifpspanel.h"
		"${SHARED_BASE_DIR}/econ/ihasowner.h"
		"${CLIENT_BASE_DIR}/ipresence.h"
		"${CLIENT_BASE_DIR}/iinput.h"
		"${CLIENT_BASE_DIR}/iloadingdisc.h"
		"${CLIENT_BASE_DIR}/imessagechars.h"
		"${CLIENT_BASE_DIR}/in_main.h"
		"${CLIENT_BASE_DIR}/inetgraphpanel.h"
		"${CLIENT_BASE_DIR}/initializer.h"
		"${CLIENT_BASE_DIR}/input.h"
		"${CLIENT_BASE_DIR}/interpolatedvar.h"
		"${CLIENT_BASE_DIR}/iprofiling.h"
		"${CLIENT_BASE_DIR}/itextmessage.h"
		"${CLIENT_BASE_DIR}/ivieweffects.h"
		"${CLIENT_BASE_DIR}/iviewrender.h"
		"${CLIENT_BASE_DIR}/iviewrender_beams.h"
		"${CLIENT_BASE_DIR}/ivmodemanager.h"
		"${CLIENT_BASE_DIR}/kbutton.h"
		"${SRCDIR}/common/language.h"
		"${CLIENT_BASE_DIR}/lerp_functions.h"
		"${CLIENT_BASE_DIR}/menu.h"
		"${CLIENT_BASE_DIR}/movehelper_client.h"
		"${CLIENT_BASE_DIR}/networkstringtable_clientdll.h"
		"${CLIENT_BASE_DIR}/panelmetaclassmgr.h"
		"${CLIENT_BASE_DIR}/particle_collision.h"
		"${CLIENT_BASE_DIR}/particle_iterators.h"
		"${CLIENT_BASE_DIR}/particle_litsmokeemitter.h"
		"${CLIENT_BASE_DIR}/particle_prototype.h"
		"${CLIENT_BASE_DIR}/particle_simple3d.h"
		"${CLIENT_BASE_DIR}/particle_util.h"
		"${CLIENT_BASE_DIR}/particledraw.h"
		"${CLIENT_BASE_DIR}/particlemgr.h"
		"${CLIENT_BASE_DIR}/particles_attractor.h"
		"${CLIENT_BASE_DIR}/particles_ez.h"
		"${CLIENT_BASE_DIR}/particles_localspace.h"
		"${CLIENT_BASE_DIR}/particles_new.h"
		"${CLIENT_BASE_DIR}/particles_simple.h"
		"${CLIENT_BASE_DIR}/particlesphererenderer.h"
		"${CLIENT_BASE_DIR}/perfvisualbenchmark.h"
		"${CLIENT_BASE_DIR}/physics.h"
		"${CLIENT_BASE_DIR}/physpropclientside.h"
		"${CLIENT_BASE_DIR}/playerandobjectenumerator.h"
		"${CLIENT_BASE_DIR}/playerenumerator.h"
		"${CLIENT_BASE_DIR}/playerspawncache.h"
		"${CLIENT_BASE_DIR}/prediction.h"
		"${CLIENT_BASE_DIR}/prediction_private.h"
		"${CLIENT_BASE_DIR}/proxyentity.h"
		"${CLIENT_BASE_DIR}/ragdoll.h"
		"${CLIENT_BASE_DIR}/ragdollexplosionenumerator.h"
		"${CLIENT_BASE_DIR}/recvproxy.h"
		"${CLIENT_BASE_DIR}/rendertexture.h"
		"${CLIENT_BASE_DIR}/ScreenSpaceEffects.h"
		"${CLIENT_BASE_DIR}/simple_keys.h"
		"${CLIENT_BASE_DIR}/smoke_fog_overlay.h"
		"${CLIENT_BASE_DIR}/splinepatch.h"
		"${CLIENT_BASE_DIR}/TeamBitmapImage.h"
		"${CLIENT_BASE_DIR}/tempent.h"
		"${CLIENT_BASE_DIR}/text_message.h"
		"${CLIENT_BASE_DIR}/timedevent.h"
		"${CLIENT_BASE_DIR}/toggletextureproxy.h"
		"${CLIENT_BASE_DIR}/vgui_basepanel.h"
		"${CLIENT_BASE_DIR}/vgui_bitmapbutton.h"
		"${CLIENT_BASE_DIR}/vgui_bitmapimage.h"
		"${CLIENT_BASE_DIR}/vgui_bitmappanel.h"
		"${CLIENT_BASE_DIR}/vgui_schemevisualizer.h"
		"${CLIENT_BASE_DIR}/vgui_entityimagepanel.h"
		"${CLIENT_BASE_DIR}/vgui_entitypanel.h"
		"${CLIENT_BASE_DIR}/vgui_grid.h"
		"${CLIENT_BASE_DIR}/vgui_helpers.h"
		"${CLIENT_BASE_DIR}/vgui_imagehealthpanel.h"
		"${CLIENT_BASE_DIR}/vgui_int.h"
		"${CLIENT_BASE_DIR}/vguicenterprint.h"
		"${CLIENT_BASE_DIR}/view.h"
		"${CLIENT_BASE_DIR}/view_scene.h"
		"${CLIENT_BASE_DIR}/viewangleanim.h"
		"${CLIENT_BASE_DIR}/ViewConeImage.h"
		"${CLIENT_BASE_DIR}/viewrender.h"
		"${CLIENT_BASE_DIR}/weapon_selection.h"
		"${CLIENT_BASE_DIR}/weapons_resource.h"
		"${CLIENT_BASE_DIR}/vgui_video.h"
		"${CLIENT_BASE_DIR}/vgui_video_player.h"
	#}

	#$Folder	"Public Header Files"
	#{
		"${SRCDIR}/public/vgui_controls/AnimationController.h"
		"${SRCDIR}/public/basehandle.h"
		"${SRCDIR}/public/tier0/basetypes.h"
		"${SRCDIR}/public/tier1/bitbuf.h"
		"${SRCDIR}/public/bitvec.h"
		"${SRCDIR}/public/bone_accessor.h"
		"${SRCDIR}/public/bone_setup.h"
		"${SRCDIR}/public/bspfile.h"
		"${SRCDIR}/public/bspflags.h"
		"${SRCDIR}/public/bsptreedata.h"
		"${SRCDIR}/public/mathlib/bumpvects.h"
		"${SRCDIR}/public/vgui_controls/Button.h"
		"${SRCDIR}/public/cdll_int.h"
		"${SRCDIR}/public/tier1/characterset.h"
		"${SRCDIR}/public/tier1/checksum_md5.h"
		"${SRCDIR}/public/client_class.h"
		"${SRCDIR}/public/client_render_handle.h"
		"${SRCDIR}/public/client_textmessage.h"
		"${SRCDIR}/public/clientstats.h"
		"${SRCDIR}/public/cmodel.h"
		"${SRCDIR}/public/vphysics/collision_set.h"
		"${SRCDIR}/public/collisionutils.h"
		"${SRCDIR}/public/Color.h"
		"${SRCDIR}/public/vgui_controls/ComboBox.h"
		"${SRCDIR}/public/tier0/commonmacros.h"
		"${SRCDIR}/public/mathlib/compressed_light_cube.h"
		"${SRCDIR}/public/mathlib/compressed_vector.h"
		"${SRCDIR}/public/con_nprint.h"
		"${SRCDIR}/public/const.h"
		"${SRCDIR}/public/vphysics/constraints.h"
		"${SRCDIR}/public/vgui_controls/Controls.h"
		"${SRCDIR}/public/tier1/convar.h"
		"${SRCDIR}/public/coordsize.h"
		"${SRCDIR}/public/crtmemdebug.h"
		"${SRCDIR}/public/vgui/Cursor.h"
		"${SRCDIR}/public/vgui/Dar.h"
		"${SRCDIR}/public/datamap.h"
		"${SRCDIR}/public/tier0/dbg.h"
		"${SRCDIR}/public/dlight.h"
		"${SRCDIR}/public/dt_common.h"
		"${SRCDIR}/public/dt_recv.h"
		"${SRCDIR}/public/dt_send.h"
		"${SRCDIR}/public/dt_utlvector_common.h"
		"${SRCDIR}/public/dt_utlvector_recv.h"
		"${SRCDIR}/public/edict.h"
		"${SRCDIR}/public/vgui_controls/EditablePanel.h"
		"${SRCDIR}/public/tier0/fasttimer.h"
		"${SRCDIR}/public/filesystem.h"
		"${SRCDIR}/public/filesystem_helpers.h"
		"${SRCDIR}/public/tier1/fmtstr.h"
		"${SRCDIR}/public/vgui_controls/FocusNavGroup.h"
		"${SRCDIR}/public/vphysics/friction.h"
		"${SRCDIR}/public/gamebspfile.h"
		"${SRCDIR}/public/gametrace.h"
		"${SRCDIR}/public/globalvars_base.h"
		"${SRCDIR}/public/vgui_controls/HTML.h"
		"${SRCDIR}/public/iachievementmgr.h"
		"${SRCDIR}/public/appframework/IAppSystem.h"
		"${SRCDIR}/public/icliententity.h"
		"${SRCDIR}/public/icliententitylist.h"
		"${SRCDIR}/public/engine/IClientLeafSystem.h"
		"${SRCDIR}/public/iclientnetworkable.h"
		"${SRCDIR}/public/vgui/IClientPanel.h"
		"${SRCDIR}/public/iclientrenderable.h"
		"${SRCDIR}/public/game/client/iclientrendertargets.h"
		"${SRCDIR}/public/iclientthinkable.h"
		"${SRCDIR}/public/iclientunknown.h"
		"${SRCDIR}/public/engine/ICollideable.h"
		"${SRCDIR}/public/tier0/icommandline.h"
		"${SRCDIR}/public/icvar.h"
		"${SRCDIR}/public/iefx.h"
		"${SRCDIR}/public/engine/IEngineSound.h"
		"${SRCDIR}/public/engine/IEngineTrace.h"
		"${SRCDIR}/public/ienginevgui.h"
		"${SRCDIR}/public/igameevents.h"
		"${SRCDIR}/public/igameresources.h"
		"${SRCDIR}/public/IGameUIFuncs.h"
		"${SRCDIR}/public/ihandleentity.h"
		"${SRCDIR}/public/vgui/IHTML.h"
		"${SRCDIR}/public/vgui/IImage.h"
		"${SRCDIR}/public/vgui/IInput.h"
		"${SRCDIR}/public/vgui/IInputInternal.h"
		"${SRCDIR}/public/vstdlib/IKeyValuesSystem.h"
		"${SRCDIR}/public/vgui/ILocalize.h"
		"${SRCDIR}/public/vgui_controls/Image.h"
		"${SRCDIR}/public/vgui_controls/ImageList.h"
		"${SRCDIR}/public/vgui_controls/ImagePanel.h"
		"${SRCDIR}/public/imapoverview.h"
		"${SRCDIR}/public/materialsystem/imaterial.h"
		"${SRCDIR}/public/materialsystem/imaterialproxy.h"
		"${SRCDIR}/public/materialsystem/imaterialsystem.h"
		"${SRCDIR}/public/materialsystem/imaterialsystemhardwareconfig.h"
		"${SRCDIR}/public/materialsystem/imaterialsystemstub.h"
		"${SRCDIR}/public/materialsystem/imaterialvar.h"
		"${SRCDIR}/public/VGuiMatSurface/IMatSystemSurface.h"
		"${SRCDIR}/public/materialsystem/imesh.h"
		"${SRCDIR}/public/inetchannelinfo.h"
		"${SRCDIR}/public/tier1/interface.h"
		"${SRCDIR}/public/interpolatortypes.h"
		"${SRCDIR}/public/vgui/IPanel.h"
		"${SRCDIR}/public/iprediction.h"
		"${SRCDIR}/public/irecipientfilter.h"
		"${SRCDIR}/public/isaverestore.h"
		"${SRCDIR}/public/vgui/IScheme.h"
		"${SRCDIR}/public/iscratchpad3d.h"
		"${SRCDIR}/public/iserverentity.h"
		"${SRCDIR}/public/iservernetworkable.h"
		"${SRCDIR}/public/iserverunknown.h"
		"${SRCDIR}/public/engine/ishadowmgr.h"
		"${SRCDIR}/public/SoundEmitterSystem/isoundemittersystembase.h"
		"${SRCDIR}/public/ispatialpartition.h"
		"${SRCDIR}/public/engine/IStaticPropMgr.h"
		"${SRCDIR}/public/istudiorender.h"
		"${SRCDIR}/public/vgui/ISurface.h"
		"${SRCDIR}/public/vgui/ISystem.h"
		"${SRCDIR}/public/materialsystem/itexture.h"
		"${SRCDIR}/public/engine/ivdebugoverlay.h"
		"${SRCDIR}/public/vgui/IVGui.h"
		"${SRCDIR}/public/ivguicenterprint.h"
		"${SRCDIR}/public/game/client/iviewport.h"
		"${SRCDIR}/public/engine/ivmodelinfo.h"
		"${SRCDIR}/public/engine/ivmodelrender.h"
		"${SRCDIR}/public/ivrenderview.h"
		"${SRCDIR}/public/jigglebones.h"
		"${SRCDIR}/public/vgui/KeyCode.h"
		"${SRCDIR}/public/tier1/KeyValues.h"
		"${SRCDIR}/public/tier0/l2cache.h"
		"${SRCDIR}/public/vgui_controls/Label.h"
		"${SRCDIR}/public/vgui_controls/ListPanel.h"
		"${SRCDIR}/public/mathlib/mathlib.h"
		"${SRCDIR}/public/tier0/mem.h"
		"${SRCDIR}/public/tier0/memalloc.h"
		"${SRCDIR}/public/tier0/memdbgoff.h"
		"${SRCDIR}/public/tier0/memdbgon.h"
		"${SRCDIR}/public/tier1/mempool.h"
		"${SRCDIR}/public/vgui_controls/Menu.h"
		"${SRCDIR}/public/vgui_controls/MenuItem.h"
		"${SRCDIR}/public/vgui_controls/MessageMap.h"
		"${SRCDIR}/public/model_types.h"
		"${SRCDIR}/public/vgui/MouseCode.h"
		"${SRCDIR}/public/mouthinfo.h"
		"${SRCDIR}/public/networkstringtabledefs.h"
		"${SRCDIR}/public/networkvar.h"
		"${SRCDIR}/public/vphysics/object_hash.h"
		"${SRCDIR}/public/overlaytext.h"
		"${SRCDIR}/public/vgui_controls/Panel.h"
		"${SRCDIR}/public/vgui_controls/PanelAnimationVar.h"
		"${SRCDIR}/public/vgui_controls/PanelListPanel.h"
		"${SRCDIR}/public/vgui_controls/PHandle.h"
		"${SRCDIR}/public/pixelwriter.h"
		"${SRCDIR}/public/tier0/platform.h"
		"${SRCDIR}/public/PlayerState.h"
		"${SRCDIR}/public/tier0/protected_things.h"
		"${SRCDIR}/public/mathlib/polyhedron.h"
		"${SRCDIR}/public/r_efx.h"
		"${SRCDIR}/public/vstdlib/random.h"
		"${SRCDIR}/public/tier1/rangecheckedvar.h"
		"${SRCDIR}/public/renamed_recvtable_compat.h"
		"${SRCDIR}/public/vgui_controls/RichText.h"
		"${SRCDIR}/public/rope_physics.h"
		"${SRCDIR}/public/rope_shared.h"
		"${SRCDIR}/public/saverestoretypes.h"
		"${SRCDIR}/public/scratchpad3d.h"
		"${SRCDIR}/public/ScratchPadUtils.h"
		"${SRCDIR}/public/vgui_controls/ScrollBar.h"
		"${SRCDIR}/public/vgui_controls/SectionedListPanel.h"
		"${SRCDIR}/public/sentence.h"
		"${SRCDIR}/public/server_class.h"
		"${SRCDIR}/public/shake.h"
		"${SRCDIR}/public/shattersurfacetypes.h"
		"${SRCDIR}/public/simple_physics.h"
		"${SRCDIR}/public/tier1/smartptr.h"
		"${SRCDIR}/public/soundchars.h"
		"${SRCDIR}/public/soundflags.h"
		"${SRCDIR}/public/soundinfo.h"
		"${SRCDIR}/public/string_t.h"
		"${SRCDIR}/public/tier1/stringpool.h"
		"${SRCDIR}/public/stringregistry.h"
		"${SRCDIR}/public/tier1/strtools.h"
		"${SRCDIR}/public/studio.h"
		"${SRCDIR}/public/surfinfo.h"
		"${SRCDIR}/public/vgui_controls/TextEntry.h"
		"${SRCDIR}/public/vgui_controls/TextImage.h"
		"${SRCDIR}/public/texture_group_names.h"
		"${SRCDIR}/public/vgui_controls/TreeView.h"
		"${SRCDIR}/public/tier1/utlbidirectionalset.h"
		"${SRCDIR}/public/tier1/utlbuffer.h"
		"${SRCDIR}/public/tier1/utldict.h"
		"${SRCDIR}/public/tier1/utlfixedmemory.h"
		"${SRCDIR}/public/tier1/utlhash.h"
		"${SRCDIR}/public/tier1/utllinkedlist.h"
		"${SRCDIR}/public/tier1/utlmap.h"
		"${SRCDIR}/public/tier1/utlmemory.h"
		"${SRCDIR}/public/tier1/utlmultilist.h"
		"${SRCDIR}/public/tier1/utlpriorityqueue.h"
		"${SRCDIR}/public/tier1/utlqueue.h"
		"${SRCDIR}/public/tier1/utlrbtree.h"
		"${SRCDIR}/public/tier1/utlstack.h"
		"${SRCDIR}/public/tier1/utlsymbol.h"
		"${SRCDIR}/public/tier1/utlvector.h"
		"${SRCDIR}/public/vcollide.h"
		"${SRCDIR}/public/vcollide_parse.h"
		"${SRCDIR}/public/mathlib/vector.h"
		"${SRCDIR}/public/mathlib/vector2d.h"
		"${SRCDIR}/public/mathlib/vector4d.h"
		"${SRCDIR}/public/vgui/VGUI.h"
		"${SRCDIR}/public/view_shared.h"
		"${SRCDIR}/public/mathlib/vmatrix.h"
		"${SRCDIR}/public/vphysics_interface.h"
		"${SRCDIR}/public/mathlib/vplane.h"
		"${SRCDIR}/public/tier0/vprof.h"
		"${SRCDIR}/public/vstdlib/vstdlib.h"
		"${SRCDIR}/public/vtf/vtf.h"
		"${SRCDIR}/public/vgui_controls/WizardPanel.h"
		"${SRCDIR}/public/vgui_controls/WizardSubPanel.h"
		"${SRCDIR}/public/worldsize.h"
		"${SRCDIR}/public/zip_uncompressed.h"
	#}

	#$Folder	"Game Shared Header Files"
	#{
		"${SHARED_BASE_DIR}/activitylist.h"
		"${SHARED_BASE_DIR}/ai_activity.h"
		"${SHARED_BASE_DIR}/ai_debug_shared.h"
		"${SHARED_BASE_DIR}/ammodef.h"
		"${SHARED_BASE_DIR}/animation.h"
		"${SHARED_BASE_DIR}/apparent_velocity_helper.h"
		"${SHARED_BASE_DIR}/base_playeranimstate.h"
		"${SHARED_BASE_DIR}/baseentity_shared.h"
		"${SHARED_BASE_DIR}/basegrenade_shared.h"
		"${SHARED_BASE_DIR}/baseparticleentity.h"
		"${SHARED_BASE_DIR}/baseplayer_shared.h"
		"${SHARED_BASE_DIR}/baseviewmodel_shared.h"
		"${SHARED_BASE_DIR}/beam_flags.h"
		"${SHARED_BASE_DIR}/beam_shared.h"
		"${SHARED_BASE_DIR}/choreoactor.h"
		"${SHARED_BASE_DIR}/choreochannel.h"
		"${SHARED_BASE_DIR}/choreoevent.h"
		"${SHARED_BASE_DIR}/choreoscene.h"
		"${SHARED_BASE_DIR}/collisionproperty.h"
		"${SHARED_BASE_DIR}/death_pose.h"
		"${SHARED_BASE_DIR}/decals.h"
		"${SHARED_BASE_DIR}/effect_color_tables.h"
		"${SHARED_BASE_DIR}/effect_dispatch_data.h"
		"${SHARED_BASE_DIR}/ehandle.h"
		"${SHARED_BASE_DIR}/entitydatainstantiator.h"
		"${SHARED_BASE_DIR}/entitylist_base.h"
		"${SHARED_BASE_DIR}/entityparticletrail_shared.h"
		"${SHARED_BASE_DIR}/env_detail_controller.h"
		"${SHARED_BASE_DIR}/env_wind_shared.h"
		"${SHARED_BASE_DIR}/eventlist.h"
		"${SHARED_BASE_DIR}/func_dust_shared.h"
		"${SHARED_BASE_DIR}/func_ladder.h"
		"${SHARED_BASE_DIR}/gameeventdefs.h"
		"${SHARED_BASE_DIR}/gamemovement.h"
		"${SHARED_BASE_DIR}/gamerules.h"
		"${SHARED_BASE_DIR}/gamerules_register.h"
		"${SHARED_BASE_DIR}/gamestats.h"
		"${SHARED_BASE_DIR}/gamestringpool.h"
		"${SHARED_BASE_DIR}/gamevars_shared.h"
		"${SHARED_BASE_DIR}/groundlink.h"
		"${SHARED_BASE_DIR}/ichoreoeventcallback.h"
		"${SHARED_BASE_DIR}/IEffects.h"
		"${SHARED_BASE_DIR}/igamemovement.h"
		"${SHARED_BASE_DIR}/igamesystem.h"
		"${SHARED_BASE_DIR}/imovehelper.h"
		"${SHARED_BASE_DIR}/in_buttons.h"
		"${SHARED_BASE_DIR}/interval.h"
		"${SHARED_BASE_DIR}/iplayeranimstate.h"
		"${SHARED_BASE_DIR}/ipredictionsystem.h"
		"${SHARED_BASE_DIR}/itempents.h"
		"${SHARED_BASE_DIR}/IVehicle.h"
		"${SHARED_BASE_DIR}/mapdata_shared.h"
		"${SHARED_BASE_DIR}/mapentities_shared.h"
		"${SHARED_BASE_DIR}/movevars_shared.h"
		"${SHARED_BASE_DIR}/multiplay_gamerules.h"
		"${SHARED_BASE_DIR}/npcevent.h"
		"${SHARED_BASE_DIR}/obstacle_pushaway.h"
		"${SHARED_BASE_DIR}/physics_saverestore.h"
		"${SHARED_BASE_DIR}/physics_shared.h"
		"${SHARED_BASE_DIR}/playernet_vars.h"
		"${SHARED_BASE_DIR}/point_posecontroller.h"
		"${SHARED_BASE_DIR}/positionwatcher.h"
		"${SHARED_BASE_DIR}/precache_register.h"
		"${SHARED_BASE_DIR}/precipitation_shared.h"
		"${SHARED_BASE_DIR}/predictable_entity.h"
		"${SHARED_BASE_DIR}/predictableid.h"
		"${SHARED_BASE_DIR}/predictioncopy.h"
		"${SHARED_BASE_DIR}/ragdoll_shared.h"
		"${SHARED_BASE_DIR}/rope_helpers.h"
		"${SHARED_BASE_DIR}/saverestore.h"
		"${SHARED_BASE_DIR}/saverestore_bitstring.h"
		"${SHARED_BASE_DIR}/saverestore_utlclass.h"
		"${SHARED_BASE_DIR}/saverestore_utlsymbol.h"
		"${SHARED_BASE_DIR}/saverestore_utlvector.h"
		"${SHARED_BASE_DIR}/sceneentity_shared.h"
		"${SHARED_BASE_DIR}/scriptevent.h"
		"${SHARED_BASE_DIR}/sequence_Transitioner.h"
		"${SHARED_BASE_DIR}/shared_classnames.h"
		"${SHARED_BASE_DIR}/shareddefs.h"
		"${SHARED_BASE_DIR}/sharedInterface.h"
		"${SHARED_BASE_DIR}/sheetsimulator.h"
		"${SHARED_BASE_DIR}/shot_manipulator.h"
		"${SHARED_BASE_DIR}/simtimer.h"
		"${SHARED_BASE_DIR}/singleplay_gamerules.h"
		"${SHARED_BASE_DIR}/smoke_fog_overlay_shared.h"
		"${SHARED_BASE_DIR}/solidsetdefaults.h"
		"${SHARED_BASE_DIR}/soundenvelope.h"
		"${SHARED_BASE_DIR}/Sprite.h"
		"${SHARED_BASE_DIR}/SpriteTrail.h"
		"${SHARED_BASE_DIR}/sun_shared.h"
		"${SHARED_BASE_DIR}/takedamageinfo.h"
		"${SHARED_BASE_DIR}/teamplay_gamerules.h"
		"${SHARED_BASE_DIR}/teamplayroundbased_gamerules.h"
		"${SHARED_BASE_DIR}/tempentity.h"
		"${SHARED_BASE_DIR}/touchlink.h"
		"${SHARED_BASE_DIR}/usercmd.h"
		"${SHARED_BASE_DIR}/usermessages.h"
		"${SHARED_BASE_DIR}/util_shared.h"
		"${SHARED_BASE_DIR}/vehicle_choreo_generic_shared.h"
		"${SHARED_BASE_DIR}/vehicle_viewblend_shared.h"
		"${SHARED_BASE_DIR}/vgui_defaultinputsignal.h"
		"${SHARED_BASE_DIR}/viewport_panel_names.h"
		"${SHARED_BASE_DIR}/voice_banmgr.h"
		"${SHARED_BASE_DIR}/voice_common.h"
		"${SHARED_BASE_DIR}/voice_gamemgr.h"
		"${SHARED_BASE_DIR}/voice_status.h"
		"${SHARED_BASE_DIR}/vphysics_sound.h"
		"${SHARED_BASE_DIR}/weapon_parse.h"
		"${SHARED_BASE_DIR}/weapon_proficiency.h"
		"${SHARED_BASE_DIR}/weapon_ifmsteadycam.h"
		"${SHARED_BASE_DIR}/mp_shareddefs.h"
	#}

	#$Folder	"game_controls Header Files"
	#{
		"${CLIENT_BASE_DIR}/game_controls/baseviewport.h"
		"${CLIENT_BASE_DIR}/game_controls/clientscoreboarddialog.h"
		"${CLIENT_BASE_DIR}/game_controls/commandmenu.h"
		"${CLIENT_BASE_DIR}/game_controls/imagemouseoverbutton.h"
		"${CLIENT_BASE_DIR}/game_controls/intromenu.h"
		"${CLIENT_BASE_DIR}/game_controls/mapoverview.h"
		"${CLIENT_BASE_DIR}/game_controls/mouseoverhtmlbutton.h"
		"${CLIENT_BASE_DIR}/game_controls/mouseoverpanelbutton.h"
		"${CLIENT_BASE_DIR}/game_controls/spectatorgui.h"
		"${CLIENT_BASE_DIR}/game_controls/teammenu.h"
		"${CLIENT_BASE_DIR}/game_controls/vguitextwindow.h"
		"${CLIENT_BASE_DIR}/game_controls/IconPanel.h"
	#}
)

set_source_files_properties(
	"${SRCDIR}/game/client/youtubeapi.cpp"
	"${SRCDIR}/common/movieobjects/timeutils.cpp"

	"${SRCDIR}/public/bone_setup.cpp"					#/
	"${SRCDIR}/public/posedebugger.cpp"					#/
	"${SRCDIR}/public/client_class.cpp"					#/
	"${SRCDIR}/common/compiledcaptionswap.cpp"			#/
	"${SRCDIR}/public/collisionutils.cpp"				#/
	"${SRCDIR}/public/crtmemdebug.cpp"					#/
	"${SRCDIR}/public/dt_recv.cpp"						#/
	"${SRCDIR}/public/dt_utlvector_common.cpp"			#/
	"${SRCDIR}/public/dt_utlvector_recv.cpp"			#/
	"${SRCDIR}/public/filesystem_helpers.cpp"			#/
	"${SRCDIR}/public/interpolatortypes.cpp"			#/
	"${SHARED_BASE_DIR}/interval.cpp"					#/
	"${SRCDIR}/common/language.cpp"						#/
	"${SRCDIR}/public/networkvar.cpp"					#/
	"${SRCDIR}/common/randoverride.cpp"					#/
	"${SRCDIR}/public/rope_physics.cpp"					#/
	"${SRCDIR}/public/scratchpad3d.cpp"					#/
	"${SRCDIR}/public/ScratchPadUtils.cpp"				#/
	"${SRCDIR}/public/sentence.cpp"						#/
	"${SHARED_BASE_DIR}/sheetsimulator.cpp"			#/
	"${SRCDIR}/public/simple_physics.cpp"				#/
	"${SRCDIR}/public/stringregistry.cpp"				#/
	"${SRCDIR}/public/studio.cpp"						#/
	"${SRCDIR}/public/vgui_controls/vgui_controls.cpp"	#/
	"${SRCDIR}/public/jigglebones.cpp"					#/
	"${CLIENT_BASE_DIR}/in_mouse.cpp"					#/
	"${SRCDIR}/public/renamed_recvtable_compat.cpp"		#/
	"${CLIENT_BASE_DIR}/rendertexture.cpp"

	PROPERTIES SKIP_PRECOMPILE_HEADERS ON
)

function( target_use_client_base target EXCLUDE_SOURCES )

	set( USED_SOURCES ${CLIENT_BASE_SOURCE_FILES} )

	if( ${EXCLUDE_SOURCES} )
		list( REMOVE_ITEM USED_SOURCES ${${EXCLUDE_SOURCES}} )
	endif()

	set_property( TARGET ${target} PROPERTY FOLDER "Game" )

	target_sources(
		${target} PRIVATE

		${USED_SOURCES}
	)

	target_include_directories(
		${target} PRIVATE

		"${CLIENT_BASE_DIR}"
		"${CLIENT_BASE_DIR}/game_controls"
		"${SHARED_BASE_DIR}"

		"${SRCDIR}/vgui2/include"
		"${SRCDIR}/vgui2/controls"
	)

	target_compile_definitions(
		${target} PRIVATE

		NO_STRING_T
		CLIENT_DLL
		VECTOR
		VERSION_SAFE_STEAM_API_INTERFACES
		PROTECTED_THINGS_ENABLE
		strncpy=use_Q_strncpy_instead
		_snprintf=use_Q_snprintf_instead
		#$<${IS_WINDOWS}:fopen=dont_use_fopen> # TODO:
		$<${IS_LINUX}:USE_WEBM_FOR_REPLAY>
	)

	target_precompile_headers(
		${target} PRIVATE
		"${CLIENT_BASE_DIR}/cbase.h"
	)

	target_link_libraries(
		${target} PRIVATE

		"$<${IS_OSX}:-framework Carbon>"
		$<$<AND:${IS_LINUX},$<NOT:${IS_ANDROID}>>:rt>
		$<${IS_WINDOWS}:winmm>
		particles

		bitmap
		choreoobjects
		dmxloader
		mathlib
		matsys_controls
		tier1
		tier2
		tier3
		vgui_controls
		vtf

		#"$<${IS_POSIX}:${LIBCOMMON}/libcrypto${STATIC_LIB_EXT}>"

		#"$<${IS_OSX}:${LIBCOMMON}/curl${STATIC_LIB_EXT}>"

		#"$<${IS_WINDOWS}:${LIBCOMMON}/libcurl${STATIC_LIB_EXT}>"
		#"$<$<OR:${IS_WINDOWS},${IS_LINUX}>:${LIBPUBLIC}/libz${STATIC_LIB_EXT}>"
		"$<${IS_WINDOWS}:${LIBPUBLIC}/libz${STATIC_LIB_EXT}>"
		"$<${IS_POSIX}:z>"

		#"$<${IS_LINUX}:${LIBCOMMON}/libcurl${STATIC_LIB_EXT}>"
		#"$<${IS_LINUX}:${LIBCOMMON}/libcurlssl${STATIC_LIB_EXT}>"

		#"$<${IS_LINUX}:${LIBCOMMON}/libssl${STATIC_LIB_EXT}>"
	)

	target_use_steamapi(
		${target}
	)
endfunction()
